package com.cloud.shopping.item.pojo;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import tk.mybatis.mapper.annotation.KeySql;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;
import java.util.List;

/**
 * SPU (Standard Product Unit) Entity
 * Represents the standard, abstract form of a product in the e-commerce system.
 * For example, "iPhone 14" is a SPU, while "iPhone 14 128GB Black" would be a SKU.
 */
@Table(name = "tb_spu")
@Data
public class Spu {
    @Id
    @KeySql(useGeneratedKeys=true)
    private Long id;
    private Long brandId;
    private Long categoryId1;    // Primary category ID
    private Long categoryId2;    // Secondary category ID
    private Long categoryId3;    // Tertiary category ID
    private String title;    // Product title
    private String subTitle;    // Product subtitle or brief description
    private Boolean saleable;    // Whether the product is available for sale

    @JsonIgnore    // Excludes this field from JSON serialization
    private Boolean valid;    // Soft delete flag - true if active, false if deleted

    private Date createTime;    // Record creation timestamp

    @JsonIgnore    // Excludes this field from JSON serialization
    private Date lastUpdateTime;    // Last modification timestamp

    /**
     * Fields marked with @Transient are not mapped to database columns.
     * These fields are used for data transfer and temporary storage during processing.
     *
     * The @Transient annotation serves two purposes:
     * 1. Excludes the field from database mapping
     * 2. Marks the field to be ignored during Java serialization
     */
    @Transient
    private String categoryName;    // Category name (derived from category service)

    @Transient
    private String brandName;    // Brand name (derived from brand service)

    @Transient
    private SpuDetail spuDetail;    // Detailed product information

    @Transient
    private List<Sku> skus;    // List of SKUs (Stock Keeping Units) for this product



    // Getters and setters are generated by Lombok @Data annotation
}
