package com.cloud.shopping.item.pojo;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Detailed information for a Standard Product Unit (SPU)
 * Contains extended product information that's too detailed for the main SPU table
 */
@Table(name="tb_spu_detail")
@Data
public class SpuDetail {
    @Id
    private Long spuId;    // Reference to the associated SPU ID
    private String description;    // Product description
    private String specialSpec;    // Template for product's special specifications and available values
    private String genericSpec;    // Product's global specification attributes
    private String packingList;    // Packing list details
    private String afterService;    // After-sales service information
    // Getters and setters are generated by Lombok @Data annotation
}