version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cloudshopping-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=cloudshopping
      - RABBITMQ_DEFAULT_PASS=cloudshopping
      - RABBITMQ_DEFAULT_VHOST=/cloudshopping
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - cloudshopping_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:

networks:
  cloudshopping_network:
    driver: bridge