server:
  port: 10086
spring:
  application:
    name: registry
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: shop1234
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka
  server:
    enableSelfPreservation: false # close self-preservation
    evictionIntervalTimerInMs: 5000 # clean service list every 5 seconds
